"""
Adaptive Learning API routes.

Endpoints:
- GET  /api/learning/recommendations
- POST /api/learning/complete-module
- POST /api/learning/regenerate-module

Behavior:
- Recommendations are ranked and refreshed after every transaction by
  `backend/ml/learning_refresh.py`.
- Module explanations are generated by Ollama and cached per (user, module)
  with a profile fingerprint. Cached content expires after 24h or when the
  user's profile changes.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timedelta
from typing import Any, Dict, Optional

import requests
from flask import Blueprint, jsonify, request

from ml.learning_recommender import get_module_registry
from ml.learning_refresh import refresh_user_learning_recommendations
from models import (
    Transaction,
    ModuleContentCache,
    LearningModuleCompletion,
    LearningRecommendationCache,
    db,
)
from utils.helpers import login_required, get_current_user

learning_bp = Blueprint("learning", __name__)


def _safe_num(x: Any, default: float = 0.0) -> float:
    try:
        if x is None:
            return default
        return float(x)
    except Exception:
        return default


def _profile_fingerprint(profile_metrics: Dict[str, Any]) -> str:
    payload = {
        "spending_profile": profile_metrics.get("spending_profile"),
        "savings_rate_percent": round(_safe_num(profile_metrics.get("savings_rate_percent")), 2),
        "survival_days": profile_metrics.get("survival_days"),
        "income_stability_score": round(_safe_num(profile_metrics.get("income_stability_score"), 0.0), 4),
        "expense_ratio": round(_safe_num(profile_metrics.get("expense_ratio")), 4),
        "dominant_category": profile_metrics.get("dominant_category"),
        "dominant_category_share": round(_safe_num(profile_metrics.get("dominant_category_share")), 4),
        "income": round(_safe_num(profile_metrics.get("income")), 2),
        "expenses": round(_safe_num(profile_metrics.get("expenses")), 2),
    }
    raw = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _limit_to_300_words(text: str) -> str:
    words = text.strip().split()
    if len(words) <= 300:
        return text.strip()
    return " ".join(words[:300]).strip()


def _registry_as_dict() -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}
    for m in get_module_registry():
        out[m.module_key] = {
            "module_key": m.module_key,
            "title": m.title,
            "module_topic": m.module_topic,
            "summary": m.summary,
            "steps": m.steps,
            "actions": m.actions,
        }
    return out


def _fallback_static_module_content(module: Dict[str, Any], profile: Dict[str, Any]) -> Dict[str, Any]:
    message = (
        "Personalized content is temporarily unavailable (AI generation failed). "
        "Here is the standard module content instead."
    )
    text = f"{message}\n\nModule: {module.get('title')}\n\nSummary: {module.get('summary')}"
    steps = module.get("steps") or []
    actions = module.get("actions") or []
    if steps:
        text += "\n\nKey steps:\n- " + "\n- ".join(steps[:3])
    if actions:
        text += "\n\nAction this week:\n- " + "\n- ".join(actions[:3])
    if profile.get("survival_days") is not None:
        text += f"\n\n(Your survival days estimate is {profile.get('survival_days')!r}.)"
    return {
        "generated_content": _limit_to_300_words(text),
        "content_source": "fallback",
        "message": message,
    }


def _compute_metrics_for_ollama(user_id: int) -> Dict[str, Any]:
    """
    Compute metrics used inside the Ollama prompt.
    """
    transactions = Transaction.query.filter_by(user_id=user_id).all()
    txs = []
    for t in transactions:
        txs.append({
            "type": t.type,
            "amount": float(t.amount or 0.0),
            "category": t.category or "Other",
            "date": t.date,
        })

    cutoff = datetime.now().date() - timedelta(days=30)

    def _parse_date(d) -> Optional[Any]:
        if isinstance(d, datetime):
            return d.date()
        if isinstance(d, str):
            try:
                return datetime.strptime(d, "%Y-%m-%d").date()
            except Exception:
                return None
        return None

    recent = []
    for t in txs:
        dt = _parse_date(t.get("date"))
        if dt is None:
            continue
        if dt >= cutoff:
            recent.append(t)

    income = sum(tt["amount"] for tt in recent if tt["type"] == "income")
    expenses = sum(tt["amount"] for tt in recent if tt["type"] == "expense")
    savings_rate_percent = ((income - expenses) / income) * 100.0 if income > 0 else None
    expense_ratio = expenses / income if income > 0 else None

    income_amounts = [tt["amount"] for tt in recent if tt["type"] == "income"]
    income_stability_score = None
    variability_index = None
    if len(income_amounts) >= 2 and sum(income_amounts) > 0:
        mean_val = sum(income_amounts) / len(income_amounts)
        variance = sum((x - mean_val) ** 2 for x in income_amounts) / len(income_amounts)
        std_val = variance ** 0.5
        variability_index = std_val / mean_val if mean_val > 0 else None
        income_stability_score = max(0.0, 1.0 - variability_index) if variability_index is not None else None

    cat_totals: Dict[str, float] = {}
    for tt in recent:
        if tt["type"] != "expense":
            continue
        cat = tt.get("category") or "Other"
        cat_totals[cat] = cat_totals.get(cat, 0.0) + float(tt.get("amount", 0.0))
    dominant_category = None
    dominant_category_share = None
    if cat_totals and expenses > 0:
        dominant_category, dominant_amt = max(cat_totals.items(), key=lambda kv: kv[1])
        dominant_category_share = dominant_amt / expenses if expenses > 0 else None

    current_balance = float(income) - float(expenses)
    try:
        from routes.analytics import _compute_survival_days_forecast, _kmeans_classify_spending_behavior

        survival_res = _compute_survival_days_forecast(txs, current_balance=current_balance)
        spend_res = _kmeans_classify_spending_behavior(txs, window_days=60, recency_double_days=30)
        spending_profile = spend_res.get("behavior")
    except Exception:
        survival_res = {"survival_days": None}
        spending_profile = None

    return {
        "spending_profile": spending_profile,
        "savings_rate_percent": savings_rate_percent,
        "survival_days": survival_res.get("survival_days"),
        "income_stability_score": income_stability_score,
        "expense_ratio": expense_ratio,
        "dominant_category": dominant_category,
        "dominant_category_share": dominant_category_share,
        "income": float(income),
        "expenses": float(expenses),
        "income_variability_index": variability_index,
    }


def _call_ollama_for_module(module_topic: str, profile_metrics: Dict[str, Any]) -> str:
    system_prompt = (
        "You are a personal financial literacy coach. "
        "The user is a student or gig worker. "
        "Generate a helpful, non-generic answer."
    )

    prompt = (
        f"{system_prompt}\n\n"
        f"User context:\n"
        f"Spending Profile is {profile_metrics.get('spending_profile')}, "
        f"Savings Rate is {profile_metrics.get('savings_rate_percent')} percent, "
        f"Survival Days is {profile_metrics.get('survival_days')}, "
        f"Income Stability Score is {profile_metrics.get('income_stability_score')}, "
        f"Expense Ratio is {profile_metrics.get('expense_ratio')}, "
        f"Dominant Spending Category is {profile_metrics.get('dominant_category')}, "
        f"Monthly Income is {profile_metrics.get('income')}, "
        f"Monthly Expenses is {profile_metrics.get('expenses')}.\n\n"
        f"The user needs to learn about {module_topic}.\n"
        f"Generate a personalized explanation of this topic in simple conversational language. "
        f"Include what this concept means, why it specifically matters given their current numbers, "
        f"and three specific actionable steps they can take this week based on their actual financial situation. "
        f"Keep the response under 300 words."
    )

    r = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": "llama3.2:latest",
            "prompt": prompt,
            "stream": False,
        },
        timeout=60,
    )
    r.raise_for_status()
    data = r.json()
    return (data.get("response") or "").strip()


def _get_or_generate_module_content(
    user_id: int,
    module: Dict[str, Any],
    profile_metrics: Dict[str, Any],
    force: bool = False,
) -> Dict[str, Any]:
    module_key = module.get("module_key")
    if not module_key:
        return {"generated_content": "", "content_source": "fallback", "message": "Invalid module."}

    profile_fp = _profile_fingerprint(profile_metrics)
    cutoff_dt = datetime.now() - timedelta(hours=24)

    if not force:
        row = (
            ModuleContentCache.query.filter_by(user_id=user_id, module_key=module_key)
            .order_by(ModuleContentCache.id.desc())
            .first()
        )
        if row is not None and row.profile_fingerprint == profile_fp:
            try:
                row_dt = datetime.strptime(row.generated_at, "%Y-%m-%d %H:%M:%S")
                if row_dt >= cutoff_dt:
                    return {
                        "generated_content": row.generated_content,
                        "content_source": row.content_source,
                        "message": "Cached content reused.",
                    }
            except Exception:
                pass

    try:
        module_topic = module.get("module_topic") or module.get("title")
        content = _call_ollama_for_module(module_topic, profile_metrics)
        content = _limit_to_300_words(content)

        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        row = ModuleContentCache.query.filter_by(user_id=user_id, module_key=module_key).first()
        if row is None:
            row = ModuleContentCache(
                user_id=user_id,
                module_key=module_key,
                profile_fingerprint=profile_fp,
                generated_content=content,
                generated_at=now_str,
                content_source="ollama",
            )
            db.session.add(row)
        else:
            row.profile_fingerprint = profile_fp
            row.generated_content = content
            row.generated_at = now_str
            row.content_source = "ollama"
        db.session.commit()

        return {
            "generated_content": content,
            "content_source": "ollama",
            "message": "Generated with Ollama.",
        }
    except Exception as e:
        fallback = _fallback_static_module_content(module, profile_metrics)
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        row = ModuleContentCache.query.filter_by(user_id=user_id, module_key=module_key).first()
        if row is None:
            row = ModuleContentCache(
                user_id=user_id,
                module_key=module_key,
                profile_fingerprint=profile_fp,
                generated_content=fallback["generated_content"],
                generated_at=now_str,
                content_source="fallback",
            )
            db.session.add(row)
        else:
            row.profile_fingerprint = profile_fp
            row.generated_content = fallback["generated_content"]
            row.generated_at = now_str
            row.content_source = "fallback"
        db.session.commit()

        return {
            "generated_content": fallback["generated_content"],
            "content_source": "fallback",
            "message": f"{fallback['message']} ({str(e)[:80]})",
        }


@learning_bp.route("/api/learning/recommendations", methods=["GET"])
@login_required
def learning_recommendations():
    user = get_current_user()
    user_id = int(user.id)

    # Refresh cached recommendations (covers first run / empty cache).
    cache = LearningRecommendationCache.query.filter_by(user_id=user_id).first()
    if not cache or not cache.recommendations_json:
        refresh_user_learning_recommendations(user_id)
        cache = LearningRecommendationCache.query.filter_by(user_id=user_id).first()

    try:
        ranked = json.loads(cache.recommendations_json or "[]")
    except Exception:
        ranked = []

    registry_map = _registry_as_dict()
    profile_metrics = _compute_metrics_for_ollama(user_id)

    out = []
    for rec in ranked:
        module_key = rec.get("module_key")
        module = registry_map.get(module_key)
        if not module:
            continue

        module["rank"] = rec.get("rank", 0)
        gen = _get_or_generate_module_content(user_id, module, profile_metrics, force=False)
        module["generated_content"] = gen.get("generated_content")
        module["content_source"] = gen.get("content_source")
        module["generated_message"] = gen.get("message")
        out.append(module)

    return jsonify({"recommendations": out})


@learning_bp.route("/api/learning/complete-module", methods=["POST"])
@login_required
def complete_learning_module():
    user = get_current_user()
    data = request.get_json(silent=True) or {}
    module_key = data.get("module_key")
    if not module_key:
        return jsonify({"error": "module_key is required"}), 400

    existing = LearningModuleCompletion.query.filter_by(user_id=user.id, module_key=module_key).first()
    if not existing:
        db.session.add(
            LearningModuleCompletion(
                user_id=user.id,
                module_key=module_key,
                completed_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            )
        )
        db.session.commit()

    refresh_user_learning_recommendations(user.id)
    return jsonify({"message": "Module marked completed", "module_key": module_key})


@learning_bp.route("/api/learning/regenerate-module", methods=["POST"])
@login_required
def regenerate_learning_module():
    user = get_current_user()
    data = request.get_json(silent=True) or {}
    module_key = data.get("module_key")
    if not module_key:
        return jsonify({"error": "module_key is required"}), 400

    registry_map = _registry_as_dict()
    module = registry_map.get(module_key)
    if not module:
        return jsonify({"error": "Invalid module_key"}), 400

    profile_metrics = _compute_metrics_for_ollama(user.id)
    gen = _get_or_generate_module_content(user.id, module, profile_metrics, force=True)
    return jsonify({
        "regenerated_module_key": module_key,
        "generated_content": gen.get("generated_content"),
        "content_source": gen.get("content_source"),
        "message": gen.get("message"),
    })

